version: 0.2

env:
  variables:
    CHROME_BIN: "/usr/bin/chromium-browser"
    # CC_TEST_REPORTER_ID:  # In CodeBuild

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install make
      # Setup for Chrome
      - apt-get install -y software-properties-common
      - add-apt-repository -y ppa:canonical-chromium-builds/stage
      # Do it!
      - apt-get update -y
      - apt-get install -y chromium-browser 
      - apt-get install -y gzip
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build
      - npm install
  build:
    commands:
      - echo Entered the build phase...
      - make test
      - make build
  post_build:
    commands:
      - ./cc-test-reporter format-coverage -t lcov --prefix ${CODEBUILD_SRC_DIR}
      - ./cc-test-reporter after-build -t lcov --exit-code $?
      - echo Entered the post_build phase...
      - ./publish.sh
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist